name: comcat
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- ipython
- jupyter
- numpy
- obspy
- pandas
- pytest
- pytest-cov
- pytest-mpl
- python=3.5
- xlrd
- xlwt
- openpyxl
- xlsxwriter
- pip:
  - ./impact-utils.zip

